CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition VARCHAR(255) NOT NULL,
    stage VARCHAR(255) NOT NULL,
    season VARCHAR(255) NOT NULL,
    home_team VARCHAR(255) NOT NULL,
    away_team VARCHAR(255) NOT NULL,
    kickoff_at TIMESTAMP(6) NOT NULL,
    stadium VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- Seed 50 match records
INSERT INTO matches (competition, stage, season, home_team, away_team, kickoff_at, stadium, status, created_at, updated_at) VALUES
('Premier League', 'Matchday 1', '2025/2026', 'Arsenal', 'Manchester United', '2025-08-17 15:00:00', 'Emirates Stadium', 2, now(), now()),
('Premier League', 'Matchday 1', '2025/2026', 'Liverpool', 'Chelsea', '2025-08-17 17:30:00', 'Anfield', 2, now(), now()),
('Premier League', 'Matchday 2', '2025/2026', 'Manchester City', 'Tottenham Hotspur', '2025-08-24 15:00:00', 'Etihad Stadium', 2, now(), now()),
('Premier League', 'Matchday 2', '2025/2026', 'Newcastle United', 'Arsenal', '2025-08-24 17:30:00', 'St James Park', 2, now(), now()),
('Premier League', 'Matchday 3', '2025/2026', 'Chelsea', 'Manchester City', '2025-08-31 15:00:00', 'Stamford Bridge', 2, now(), now()),
('Premier League', 'Matchday 10', '2025/2026', 'Manchester United', 'Liverpool', '2025-11-02 16:30:00', 'Old Trafford', 0, now(), now()),
('Premier League', 'Matchday 11', '2025/2026', 'Tottenham Hotspur', 'Newcastle United', '2025-11-09 15:00:00', 'Tottenham Hotspur Stadium', 0, now(), now()),
('Premier League', 'Matchday 15', '2025/2026', 'Arsenal', 'Chelsea', '2025-12-14 16:30:00', 'Emirates Stadium', 0, now(), now()),
('Premier League', 'Matchday 20', '2025/2026', 'Liverpool', 'Manchester City', '2026-01-18 16:30:00', 'Anfield', 0, now(), now()),
('Premier League', 'Matchday 25', '2025/2026', 'Manchester United', 'Arsenal', '2026-02-22 15:00:00', 'Old Trafford', 0, now(), now()),
('La Liga', 'Jornada 1', '2025/2026', 'Real Madrid', 'Barcelona', '2025-08-16 20:00:00', 'Santiago Bernabeu', 2, now(), now()),
('La Liga', 'Jornada 2', '2025/2026', 'Atletico Madrid', 'Sevilla', '2025-08-23 19:00:00', 'Civitas Metropolitano', 2, now(), now()),
('La Liga', 'Jornada 3', '2025/2026', 'Barcelona', 'Valencia', '2025-08-30 21:00:00', 'Spotify Camp Nou', 2, now(), now()),
('La Liga', 'Jornada 12', '2025/2026', 'Real Madrid', 'Atletico Madrid', '2025-11-08 21:00:00', 'Santiago Bernabeu', 0, now(), now()),
('La Liga', 'Jornada 18', '2025/2026', 'Sevilla', 'Real Madrid', '2025-12-20 18:30:00', 'Ramon Sanchez Pizjuan', 0, now(), now()),
('La Liga', 'Jornada 24', '2025/2026', 'Valencia', 'Barcelona', '2026-02-01 20:00:00', 'Mestalla', 0, now(), now()),
('Serie A', 'Giornata 1', '2025/2026', 'Juventus', 'AC Milan', '2025-08-24 20:45:00', 'Allianz Stadium', 2, now(), now()),
('Serie A', 'Giornata 2', '2025/2026', 'Inter Milan', 'AS Roma', '2025-08-31 18:00:00', 'San Siro', 2, now(), now()),
('Serie A', 'Giornata 3', '2025/2026', 'Napoli', 'Juventus', '2025-09-07 20:45:00', 'Stadio Diego Armando Maradona', 2, now(), now()),
('Serie A', 'Giornata 14', '2025/2026', 'AC Milan', 'Inter Milan', '2025-11-30 20:45:00', 'San Siro', 0, now(), now()),
('Serie A', 'Giornata 20', '2025/2026', 'AS Roma', 'Napoli', '2026-01-11 18:00:00', 'Stadio Olimpico', 0, now(), now()),
('Bundesliga', 'Spieltag 1', '2025/2026', 'Bayern Munich', 'Borussia Dortmund', '2025-08-22 18:30:00', 'Allianz Arena', 2, now(), now()),
('Bundesliga', 'Spieltag 2', '2025/2026', 'RB Leipzig', 'Bayer Leverkusen', '2025-08-29 15:30:00', 'Red Bull Arena', 2, now(), now()),
('Bundesliga', 'Spieltag 3', '2025/2026', 'Borussia Dortmund', 'RB Leipzig', '2025-09-05 15:30:00', 'Signal Iduna Park', 2, now(), now()),
('Bundesliga', 'Spieltag 16', '2025/2026', 'Bayer Leverkusen', 'Bayern Munich', '2025-12-13 18:30:00', 'BayArena', 0, now(), now()),
('Bundesliga', 'Spieltag 22', '2025/2026', 'Bayern Munich', 'RB Leipzig', '2026-01-24 18:30:00', 'Allianz Arena', 0, now(), now()),
('Ligue 1', 'Journee 1', '2025/2026', 'Paris Saint-Germain', 'Marseille', '2025-08-17 20:45:00', 'Parc des Princes', 2, now(), now()),
('Ligue 1', 'Journee 2', '2025/2026', 'Lyon', 'Monaco', '2025-08-24 17:00:00', 'Groupama Stadium', 2, now(), now()),
('Ligue 1', 'Journee 3', '2025/2026', 'Marseille', 'Lyon', '2025-08-31 20:45:00', 'Orange Velodrome', 2, now(), now()),
('Ligue 1', 'Journee 15', '2025/2026', 'Monaco', 'Paris Saint-Germain', '2025-12-07 20:45:00', 'Stade Louis II', 0, now(), now()),
('UEFA Champions League', 'Group Stage MD1', '2025/2026', 'Real Madrid', 'Bayern Munich', '2025-09-16 21:00:00', 'Santiago Bernabeu', 2, now(), now()),
('UEFA Champions League', 'Group Stage MD1', '2025/2026', 'Manchester City', 'Inter Milan', '2025-09-17 21:00:00', 'Etihad Stadium', 2, now(), now()),
('UEFA Champions League', 'Group Stage MD2', '2025/2026', 'Barcelona', 'Paris Saint-Germain', '2025-10-01 21:00:00', 'Spotify Camp Nou', 2, now(), now()),
('UEFA Champions League', 'Round of 16', '2025/2026', 'Liverpool', 'Juventus', '2026-02-18 21:00:00', 'Anfield', 0, now(), now()),
('UEFA Champions League', 'Quarter Final', '2025/2026', 'Manchester City', 'Real Madrid', '2026-04-08 21:00:00', 'Etihad Stadium', 3, now(), now()),
('UEFA Champions League', 'Final', '2025/2026', 'Bayern Munich', 'Barcelona', '2026-05-30 21:00:00', 'Wembley Stadium', 0, now(), now()),
('UEFA Europa League', 'Group Stage MD1', '2025/2026', 'Tottenham Hotspur', 'AS Roma', '2025-09-25 21:00:00', 'Tottenham Hotspur Stadium', 2, now(), now()),
('UEFA Europa League', 'Round of 16', '2025/2026', 'Napoli', 'Sevilla', '2026-03-12 21:00:00', 'Stadio Diego Armando Maradona', 0, now(), now()),
('FA Cup', 'Third Round', '2025/2026', 'Newcastle United', 'Chelsea', '2026-01-05 15:00:00', 'St James Park', 0, now(), now()),
('FA Cup', 'Fourth Round', '2025/2026', 'Arsenal', 'Manchester City', '2026-01-25 15:00:00', 'Emirates Stadium', 0, now(), now()),
('Copa del Rey', 'Round of 16', '2025/2026', 'Valencia', 'Atletico Madrid', '2026-01-14 20:00:00', 'Mestalla', 0, now(), now()),
('DFB-Pokal', 'Quarter Final', '2025/2026', 'Borussia Dortmund', 'Bayer Leverkusen', '2026-02-04 20:45:00', 'Signal Iduna Park', 0, now(), now()),
('Coupe de France', 'Round of 16', '2025/2026', 'Lyon', 'Marseille', '2026-01-21 21:00:00', 'Groupama Stadium', 0, now(), now()),
('World Cup Qualifiers', 'Group A', '2025/2026', 'Brazil', 'Argentina', '2025-09-09 20:00:00', 'Maracana', 2, now(), now()),
('World Cup Qualifiers', 'Group B', '2025/2026', 'Germany', 'Spain', '2025-10-14 20:45:00', 'Olympiastadion Berlin', 4, now(), now()),
('International Friendly', 'Friendly', '2025/2026', 'England', 'France', '2025-11-18 20:00:00', 'Wembley Stadium', 2, now(), now()),
('International Friendly', 'Friendly', '2025/2026', 'Portugal', 'Italy', '2025-11-19 20:45:00', 'Estadio da Luz', 2, now(), now()),
('Premier League', 'Matchday 30', '2025/2026', 'Chelsea', 'Newcastle United', '2026-03-28 15:00:00', 'Stamford Bridge', 0, now(), now()),
('Premier League', 'Matchday 33', '2025/2026', 'Tottenham Hotspur', 'Liverpool', '2026-04-18 15:00:00', 'Tottenham Hotspur Stadium', 0, now(), now()),
('La Liga', 'Jornada 30', '2025/2026', 'Atletico Madrid', 'Barcelona', '2026-03-15 21:00:00', 'Civitas Metropolitano', 0, now(), now());

CREATE TABLE IF NOT EXISTS ticket_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES matches(id),
    name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- Seed ticket types for a selection of matches (VIP / Category 1 / General Admission)
INSERT INTO ticket_types (match_id, name, price, quantity, available_quantity, created_at, updated_at)
SELECT m.id, t.name, t.price, t.quantity, t.available_quantity, now(), now()
FROM matches m
JOIN (VALUES
    ('Arsenal', 'Manchester United', 'VIP', 500000, 500, 500),
    ('Arsenal', 'Manchester United', 'Category 1', 300000, 3000, 3000),
    ('Arsenal', 'Manchester United', 'General Admission', 150000, 15000, 15000),

    ('Liverpool', 'Chelsea', 'VIP', 500000, 500, 500),
    ('Liverpool', 'Chelsea', 'Category 1', 300000, 3000, 3000),
    ('Liverpool', 'Chelsea', 'General Admission', 150000, 15000, 15000),

    ('Manchester United', 'Arsenal', 'VIP', 550000, 500, 120),
    ('Manchester United', 'Arsenal', 'Category 1', 320000, 3200, 900),
    ('Manchester United', 'Arsenal', 'General Admission', 160000, 16000, 4500),

    ('Real Madrid', 'Barcelona', 'VIP', 1200000, 800, 60),
    ('Real Madrid', 'Barcelona', 'Category 1', 700000, 4000, 500),
    ('Real Madrid', 'Barcelona', 'General Admission', 350000, 20000, 3200),

    ('Atletico Madrid', 'Barcelona', 'VIP', 600000, 400, 400),
    ('Atletico Madrid', 'Barcelona', 'Category 1', 350000, 2500, 2500),
    ('Atletico Madrid', 'Barcelona', 'General Admission', 180000, 12000, 12000),

    ('Juventus', 'AC Milan', 'VIP', 500000, 450, 450),
    ('Juventus', 'AC Milan', 'Category 1', 280000, 2800, 2800),
    ('Juventus', 'AC Milan', 'General Admission', 140000, 14000, 14000),

    ('Bayern Munich', 'Borussia Dortmund', 'VIP', 550000, 500, 500),
    ('Bayern Munich', 'Borussia Dortmund', 'Category 1', 300000, 3000, 3000),
    ('Bayern Munich', 'Borussia Dortmund', 'General Admission', 150000, 15000, 15000),

    ('Paris Saint-Germain', 'Marseille', 'VIP', 500000, 400, 400),
    ('Paris Saint-Germain', 'Marseille', 'Category 1', 280000, 2500, 2500),
    ('Paris Saint-Germain', 'Marseille', 'General Admission', 140000, 13000, 13000),

    ('Real Madrid', 'Bayern Munich', 'VIP', 900000, 600, 600),
    ('Real Madrid', 'Bayern Munich', 'Category 1', 550000, 3500, 3500),
    ('Real Madrid', 'Bayern Munich', 'General Admission', 280000, 18000, 18000),

    ('Manchester City', 'Real Madrid', 'VIP', 1000000, 700, 700),
    ('Manchester City', 'Real Madrid', 'Category 1', 600000, 3800, 3800),
    ('Manchester City', 'Real Madrid', 'General Admission', 300000, 19000, 19000),

    ('Bayern Munich', 'Barcelona', 'VIP', 1500000, 900, 30),
    ('Bayern Munich', 'Barcelona', 'Category 1', 900000, 5000, 200),
    ('Bayern Munich', 'Barcelona', 'General Admission', 450000, 25000, 1800),

    ('Newcastle United', 'Chelsea', 'VIP', 450000, 350, 350),
    ('Newcastle United', 'Chelsea', 'Category 1', 250000, 2200, 2200),
    ('Newcastle United', 'Chelsea', 'General Admission', 130000, 11000, 11000),

    ('Arsenal', 'Manchester City', 'VIP', 500000, 500, 500),
    ('Arsenal', 'Manchester City', 'Category 1', 300000, 3000, 3000),
    ('Arsenal', 'Manchester City', 'General Admission', 150000, 15000, 15000),

    ('Brazil', 'Argentina', 'VIP', 800000, 1000, 1000),
    ('Brazil', 'Argentina', 'Category 1', 450000, 6000, 6000),
    ('Brazil', 'Argentina', 'General Admission', 220000, 30000, 30000),

    ('England', 'France', 'VIP', 600000, 700, 700),
    ('England', 'France', 'Category 1', 350000, 4500, 4500),
    ('England', 'France', 'General Admission', 180000, 20000, 20000)
) AS t(home_team, away_team, name, price, quantity, available_quantity)
    ON t.home_team = m.home_team AND t.away_team = m.away_team AND m.season = '2025/2026';
